server:
  port: ${SERVER_PORT_EXPOSE:8080}

spring:
  flyway:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:geros}?createDatabaseIfNotExist=${DATABASE_CREATE_IF_NOT_EXISTS:true}
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    schemas:
      - ${DATABASE:geros}
  application:
    name: geros
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:geros}?createDatabaseIfNotExist=${DATABASE_CREATE_IF_NOT_EXISTS:true}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    platform: Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 450
      minimum-idle: 50
      idle-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:none}
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        jdbc:
          time_zone: UTC
          batch_size: ${JBDC_BATCH_SIZE:50}
      type: trace

jwt:
  secret: ${JWT_SECRET:123}
  expiration: ${JWT_EXPIRATION:21600000}
